apiVersion: v2
version: 80.8.0
name: prometheus-community
dependencies:
  - name: kube-prometheus-stack
    version: 80.8.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: monitoring
  - name: prometheus-blackbox-exporter
    version: 11.6.1
    repository: https://prometheus-community.github.io/helm-charts
    alias: blackbox-exporter
