{{- if .Values.templates.dashboard_hostname }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tls-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.templates.dashboard_hostname }}`)
      kind: Rule
      {{- if .Values.templates.dashboard_auth }}
      middlewares:
      - name: auth
      {{- end }}
      services:
      - name: api@internal
        kind: TraefikService
{{- end }}
{{- if .Values.templates.http_redirect.enable }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-http-redirect
spec:
  entryPoints:
  - web
  routes:
  - match: HostRegexp(`{catchall:.*}`)
    kind: Rule
    {{- if .Values.templates.http_redirect.priority }}
    priority: {{ .Values.templates.http_redirect.priority | quote }}
    {{ else }}
    priority: 1
    {{- end }}
    services:
    - name: noop@internal
      kind: TraefikService
    middlewares:
        - name: http-redirect
{{- end }}

