apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default

{{- if .Values.templates.default_cert }}
spec:
  defaultCertificate:
    secretName:  {{ .Values.templates.default_cert }}
{{- end }}

